#!/bin/bash
export COMPRESSION="NONE"
echo "Sleeping for 20 seconds to give HBase time to warm up"
sleep 20

if [ ! -e /opt/opentsdb_tables_created.txt ]; then
	echo "creating tsdb tables"
  /usr/share/opentsdb/tools/create_table.sh
  touch /opt/opentsdb_tables_created.txt
	echo "created tsdb tables"
fi

echo "starting opentsdb"
exec 2>&1
exec /usr/share/opentsdb/bin/tsdb tsd
