#!/bin/bash

IP=`ip addr show eth0 | grep 'inet ' | cut -d/ -f1 | awk '{print $2}'`

sed -i "s/@IP@/$IP/g" /opt/hbase/conf/hbase-site.xml

sed -i "s/@IP@/$IP/g" /opt/hbase/conf/zoo.cfg

echo "$IP $(hostname)" >> /etc/hosts

exec 2>&1
exec $HBASE_SERVER master start 2>&1
